mysite/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed
from search.views import search_blog_view

urlpatterns = [
    url(r'^feeds/$', LatestPostsFeed(), name='latest-post-feed'),
    url(r'^search/$', search_blog_view, name='search'),
    url(r'^$', views.post_list, name='post-list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)$', views.post_list,
        name='post-list-by-tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post-detail'),
    url(r'^(?P<post_id>\d+)/share/email', views.post_share, name='share-email')
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog'))
]

mysite/blog/models.py
from django.db import models
from django.db.models import Count
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, 
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

    def get_similiar_posts(self, count=4):
        post_tags_ids = self.tags.values_list('id', flat=True)
        similiar_posts = Post.published.filter(tags__in=post_tags_ids)\
                .exclude(id=self.id)
        similiar_posts = similiar_posts.annotate(same_tags=Count('tags'))\
                .order_by('-same_tags', '-publish')[:count]
        return similiar_posts

mysite/search/models.py
from django.db import models

# Create your models here.

mysite/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, 
                           widget=forms.TextInput({'class': 'form-control mb-2'}))
    email = forms.EmailField(widget=forms.TextInput({'class': 'form-control mb-2'}))
    to = forms.EmailField(widget=forms.TextInput({'class': 'form-control mb-2'}))
    comment = forms.CharField(widget=forms.Textarea({'class': 'form-control mb-2'}), required=False)

mysite/search/forms.py
from django import forms

class SearchForm(forms.Form):
    q = forms.CharField(label='')

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from taggit.models import Tag


from .models import Post
from .forms import EmailPostForm

from comments.forms import CommentForm

# Create your views here.

def post_share(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    data = {}
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

            post_url = request.build_absolute_uri(
                post.get_absolute_url())

            subject = '{} ({}) recommends you reading {}'.format(
                data['name'], data['email'], post.title)
            message = 'Read "{}" at {}\n\nComment:\n{}'.format(
                post.title, post_url, data.get('comment', 'No comment'))

            sending = send_mail(subject, message, data['email'], [data['to']],
                                fail_silently=False)

            if sending:
                sent = True

    else:
        form = EmailPostForm()
    
    context = {
        "post": post,
        "form": form,
        "sent" : sent,
        "form_data": data
    }

    return render(request,
                  'blog/post/share_email.html',
                  context)



class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'



def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 2)

    page = request.GET.get('page', 1)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'page': page,
        'tag': tag
    }

    return render(request,
                  'blog/post/list.html',
                  context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    similiar_posts = post.get_similiar_posts()

    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'similiar_posts': similiar_posts
    }

    return render(request,
                  'blog/post/detail.html',
                  context)

mysite/search/views.py
from django.shortcuts import render
from haystack.query import SearchQuerySet

from .forms import SearchForm
from blog.models import Post

# Create your views here.
def search_blog_view(request):
    form = SearchForm()
    results = []
    total = 0
    data = []

    if 'q' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            data = form.cleaned_data

            results = SearchQuerySet().models(Post).highlight()\
                    .filter(content=data['q']).load_all()
            total = results.count()

    context = {
        'form': form,
        'results': results,
        'total': total,
        'data': data
    }

    return render(request,
                  'blog/post/search.html',
                  context)

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block site_title %}{{ post.title | title }}{% endblock %}

{% block main_content %}



<h1 class="my-4">{{ post.title | title }}
  <small class="text-muted">Posted on {{ post.publish }} by {{ post.author.username }}</small>
</h1>


    <!-- Blog Post -->
    <div class="card mb-4">
      {% with post.tags.all as tags %}
          {% if tags %}
          <div class="card-header">Tags: 
            {% for tag in tags %}
              <a href="{% url 'blog:post-list-by-tag' tag.slug %}">{{ tag }}</a>
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
      <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
      <div class="card-body">
        <p class="card-text"> {{ post.body | markdown | linebreaks }}</p>
      </div>
      <div class="card-footer text-muted">
        <a class="card-link" href="{% url 'blog:share-email' post.id %}">share by email</a>
      </div>
    </div>

    <div class="card mb-4">
      <div class="card-header">Similiar Posts</div>
      <div class="card-body">
        {% for similiar in similiar_posts %}
          <p><a href="{{ similiar.get_absolute_url }}">{{ similiar.title | title }}</a></p>
        {% empty %}
          <p>There are no similiar posts.</p>
        {% endfor %}

      </div>
    </div>

    <div class="card mb-4">
      {% with comments.count as total_count %}
        <div class="card-header">{{ total_count }} comment{{ total_count|pluralize }}</div>
      {% endwith %}

      {% for comment in comments %}

					<div class="media m-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{ comment.name }}</h5>
              {{ comment.body | linebreaks }} 
            </div>
          </div>

      {% endfor %}

      <div class="card-body">
        <form action="{{ post.get_absolute_url }}" method="post">
          {% csrf_token %}
          {{ form }}

          <input class="btn btn-success" type="submit" value="Submit">
        </form>
      </div>
    </div>


        
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
  <li><a href="{{ post.get_absolute_url }}">{{ post.title | title }}</a></li>
  {% empty %}
  <p>No post yet here.</p>
  {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block site_title %}{% if tag %}{{ tag }}{% else %}Blog Posts{% endif %}{% endblock %}

{% block main_content %}

{% if tag %}
<h1 class="my-4">Posts with tag '{{ tag }}'</h1>
{% else %}
<h1 class="my-4">Blog Posts </h1>
{% endif %}

{% if posts %}

{% for post in posts %}
    <!-- Blog Post -->
    <div class="card mb-4">
      {% with post.tags.all as tags %}
          {% if tags %}
          <div class="card-header">Tags: 
            {% for tag in tags %}
              <a href="{% url 'blog:post-list-by-tag' tag.slug %}">{{ tag }}</a>
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
      <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
      <div class="card-body">
        <h2 class="card-title">{{ post.title }}</h2>
        <p class="card-text"> {{ post.body | markdown | truncatewords_html:20 }}</p>
        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
      </div>
      <div class="card-footer text-muted">
        Posted on {{ post.publish }} by
        <a href="#">{{ post.author.username }}</a>
      </div>
    </div>

{% endfor %}

{% include 'pagination.html' with page=posts %}

{% else %}
<p>No post found.</p>
{% endif %}

        
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block site_title %}Search result of {{ data.q }}{% endblock %}

{% block main_content %}

{% if 'q' in request.GET %}
  <h1 class="my-4">Posts containing {{ data.q }}</h1>
  <h3>Found {{ total }} result{{ total|pluralize }}</h3>
  {% for post in results %}
      <!-- Blog Post -->
      <div class="card mb-4">
        {% with post.tags.all as tags %}
            {% if tags %}
            <div class="card-header">Tags: 
              {% for tag in tags %}
                <a href="{% url 'blog:post-list-by-tag' tag.slug %}">{{ tag }}</a>
                {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
        <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
        <div class="card-body">
          <h2 class="card-title">{{ post.object.title }}</h2>
          <p class="card-text"> {{ post.highlighted.text.0 | safe }}</p>
          <a href="{{ post.object.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          Posted on {{ post.publish }} by
          <a href="#">{{ post.object.author.username }}</a>
        </div>
      </div>

      {% empty %}
      <p>There are no results for your query.</p>


  {% endfor %}
{% else %}
<h1 class="my-4">Search for Posts</h1>
{% include 'search/snippets/search_form.html' %}
{% endif %}




        
{% endblock %}

mysite/blog/templates/blog/post/share_email.html
{% extends 'blog/base.html' %}

{% block site_title %}Share {{ post.title | title }}{% endblock %}

{% block main_content %}



<h1 class="my-4">Share {{ post.title | title }}</h1>


    <!-- Blog Post -->
    <div class="card mb-4">
      <div class="card-body">

        {% if sent %}
          <p>Your email sent successfully to {{ form_data.to }}</p>
        {% else %}
          <form action="{% url 'blog:share-email' post.id %}" method="post">
            {% csrf_token %}
            {{ form }}

            <input class="btn btn-success" type="submit" value="submit">
            
          </form>
        {% endif %}
      </div>
    </div>


        
{% endblock %}